apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-green
  labels:
    app: orders
    version: green
spec:
  replicas: 2
  revisionHistoryLimit: 10  
  selector:
    matchLabels:
      app: orders
      version: green
  template:
    metadata:
      labels:
        app: orders
        version: green
    spec:
      containers:
      - name: orders
        image: 637423638685.dkr.ecr.us-east-1.amazonaws.com/ciclo-final:${GITHUB_SHA}
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 20
