name: CI/CD Robusto

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  run-precario:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo central
        uses: actions/checkout@v4
        with:
          repository: sebastian1219/repo-principal
          path: repo-principal
          fetch-depth: 0

      - name: Mostrar workflow precario
        run: cat repo-principal/.github/workflows/terraform-precario.yml

  validate-and-deploy:
    needs: run-precario
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo robusto
        uses: actions/checkout@v4

      - name: Validaciones Terraform
        run: |
          terraform init
          terraform validate

      - name: TFLint
        run: |
          tflint --init
          tflint --recursive

      - name: Checkov
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          soft_fail: false

      - name: Deploy Green
        run: kubectl apply -f manifiestos/deployment-green.yaml

      - name: Health Check
        run: |
          kubectl rollout status deployment/orders-green --timeout=60s
          curl -f http://orders-green.$DOMAIN/health || exit 1

      - name: Switch Traffic
        run: kubectl apply -f manifiestos/service-green.yaml

  rollback:
    needs: validate-and-deploy
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Rollback
        run: |
          kubectl apply -f manifiestos/service-blue.yaml
          kubectl rollout undo deployment/orders-green
